FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt requirements-dev.txt requirements-quality.txt ./
RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt -r requirements-quality.txt

COPY . /app

ENTRYPOINT ["bash", "-lc"]
CMD ["python -m librariarr.main --config /config/config.yaml --log-level DEBUG"]
